//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pia.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pia.Resources.Strings.MessageStrings", typeof(MessageStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Column Added.
        /// </summary>
        public static string Kanban_ColumnAdded {
            get {
                return ResourceManager.GetString("Kanban_ColumnAdded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Column &quot;{0}&quot; has been added to the board..
        /// </summary>
        public static string Kanban_ColumnAddedDetail {
            get {
                return ResourceManager.GetString("Kanban_ColumnAddedDetail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter column name:.
        /// </summary>
        public static string Kanban_ColumnNamePrompt {
            get {
                return ResourceManager.GetString("Kanban_ColumnNamePrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot delete a column that contains todos. Move or delete all todos first..
        /// </summary>
        public static string Kanban_ColumnNotEmpty {
            get {
                return ResourceManager.GetString("Kanban_ColumnNotEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the column &quot;{0}&quot;?.
        /// </summary>
        public static string Kanban_DeleteColumnConfirm {
            get {
                return ResourceManager.GetString("Kanban_DeleteColumnConfirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copied.
        /// </summary>
        public static string Msg_Assistant_Copied {
            get {
                return ResourceManager.GetString("Msg_Assistant_Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current value:.
        /// </summary>
        public static string Msg_Assistant_CurrentValue {
            get {
                return ResourceManager.GetString("Msg_Assistant_CurrentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Updated.
        /// </summary>
        public static string Msg_Assistant_MemoryUpdated {
            get {
                return ResourceManager.GetString("Msg_Assistant_MemoryUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message copied to clipboard..
        /// </summary>
        public static string Msg_Assistant_MessageCopied {
            get {
                return ResourceManager.GetString("Msg_Assistant_MessageCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New value:.
        /// </summary>
        public static string Msg_Assistant_NewValue {
            get {
                return ResourceManager.GetString("Msg_Assistant_NewValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No AI provider configured for Assistant mode. Please add one in Settings..
        /// </summary>
        public static string Msg_Assistant_NoProviderConfigured {
            get {
                return ResourceManager.GetString("Msg_Assistant_NoProviderConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No AI provider configured. Please add one in Settings..
        /// </summary>
        public static string Msg_Assistant_NoProviderInline {
            get {
                return ResourceManager.GetString("Msg_Assistant_NoProviderInline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will permanently delete this memory..
        /// </summary>
        public static string Msg_Assistant_PermanentDeleteMemory {
            get {
                return ResourceManager.GetString("Msg_Assistant_PermanentDeleteMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will permanently delete this reminder..
        /// </summary>
        public static string Msg_Assistant_PermanentDeleteReminder {
            get {
                return ResourceManager.GetString("Msg_Assistant_PermanentDeleteReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will permanently delete this todo..
        /// </summary>
        public static string Msg_Assistant_PermanentDeleteTodo {
            get {
                return ResourceManager.GetString("Msg_Assistant_PermanentDeleteTodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder Updated.
        /// </summary>
        public static string Msg_Assistant_ReminderUpdated {
            get {
                return ResourceManager.GetString("Msg_Assistant_ReminderUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response generation was cancelled..
        /// </summary>
        public static string Msg_Assistant_ResponseCancelled {
            get {
                return ResourceManager.GetString("Msg_Assistant_ResponseCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get AI response: {0}.
        /// </summary>
        public static string Msg_Assistant_ResponseFailed {
            get {
                return ResourceManager.GetString("Msg_Assistant_ResponseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking memory....
        /// </summary>
        public static string Msg_Assistant_StatusCheckingMemory {
            get {
                return ResourceManager.GetString("Msg_Assistant_StatusCheckingMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking reminders....
        /// </summary>
        public static string Msg_Assistant_StatusCheckingReminders {
            get {
                return ResourceManager.GetString("Msg_Assistant_StatusCheckingReminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking todos....
        /// </summary>
        public static string Msg_Assistant_StatusCheckingTodos {
            get {
                return ResourceManager.GetString("Msg_Assistant_StatusCheckingTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completing todo....
        /// </summary>
        public static string Msg_Assistant_StatusCompletingTodo {
            get {
                return ResourceManager.GetString("Msg_Assistant_StatusCompletingTodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating memory....
        /// </summary>
        public static string Msg_Assistant_StatusCreatingMemory {
            get {
                return ResourceManager.GetString("Msg_Assistant_StatusCreatingMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating reminder....
        /// </summary>
        public static string Msg_Assistant_StatusCreatingReminder {
            get {
                return ResourceManager.GetString("Msg_Assistant_StatusCreatingReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating todo....
        /// </summary>
        public static string Msg_Assistant_StatusCreatingTodo {
            get {
                return ResourceManager.GetString("Msg_Assistant_StatusCreatingTodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting memory....
        /// </summary>
        public static string Msg_Assistant_StatusDeletingMemory {
            get {
                return ResourceManager.GetString("Msg_Assistant_StatusDeletingMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting reminder....
        /// </summary>
        public static string Msg_Assistant_StatusDeletingReminder {
            get {
                return ResourceManager.GetString("Msg_Assistant_StatusDeletingReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting todo....
        /// </summary>
        public static string Msg_Assistant_StatusDeletingTodo {
            get {
                return ResourceManager.GetString("Msg_Assistant_StatusDeletingTodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        public static string Msg_Assistant_StatusProcessing {
            get {
                return ResourceManager.GetString("Msg_Assistant_StatusProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching memory....
        /// </summary>
        public static string Msg_Assistant_StatusSearchingMemory {
            get {
                return ResourceManager.GetString("Msg_Assistant_StatusSearchingMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thinking....
        /// </summary>
        public static string Msg_Assistant_StatusThinking {
            get {
                return ResourceManager.GetString("Msg_Assistant_StatusThinking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating memory....
        /// </summary>
        public static string Msg_Assistant_StatusUpdatingMemory {
            get {
                return ResourceManager.GetString("Msg_Assistant_StatusUpdatingMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating reminder....
        /// </summary>
        public static string Msg_Assistant_StatusUpdatingReminder {
            get {
                return ResourceManager.GetString("Msg_Assistant_StatusUpdatingReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating todo....
        /// </summary>
        public static string Msg_Assistant_StatusUpdatingTodo {
            get {
                return ResourceManager.GetString("Msg_Assistant_StatusUpdatingTodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todo Updated.
        /// </summary>
        public static string Msg_Assistant_TodoUpdated {
            get {
                return ResourceManager.GetString("Msg_Assistant_TodoUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value:.
        /// </summary>
        public static string Msg_Assistant_Value {
            get {
                return ResourceManager.GetString("Msg_Assistant_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string Msg_Cancelled {
            get {
                return ResourceManager.GetString("Msg_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Msg_Error {
            get {
                return ResourceManager.GetString("Msg_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this session? This action cannot be undone..
        /// </summary>
        public static string Msg_History_ConfirmDeleteMessage {
            get {
                return ResourceManager.GetString("Msg_History_ConfirmDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Session.
        /// </summary>
        public static string Msg_History_ConfirmDeleteTitle {
            get {
                return ResourceManager.GetString("Msg_History_ConfirmDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy to clipboard: {0}.
        /// </summary>
        public static string Msg_History_CopyFailed {
            get {
                return ResourceManager.GetString("Msg_History_CopyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete session: {0}.
        /// </summary>
        public static string Msg_History_DeleteSessionFailed {
            get {
                return ResourceManager.GetString("Msg_History_DeleteSessionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Fresh.
        /// </summary>
        public static string Msg_Memory_AllFresh {
            get {
                return ResourceManager.GetString("Msg_Memory_AllFresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...and {0} more..
        /// </summary>
        public static string Msg_Memory_AndMore {
            get {
                return ResourceManager.GetString("Msg_Memory_AndMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaned Up.
        /// </summary>
        public static string Msg_Memory_CleanedUp {
            get {
                return ResourceManager.GetString("Msg_Memory_CleanedUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string Msg_Memory_Complete {
            get {
                return ResourceManager.GetString("Msg_Memory_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to delete all stale memories?.
        /// </summary>
        public static string Msg_Memory_DeleteAllStaleQuestion {
            get {
                return ResourceManager.GetString("Msg_Memory_DeleteAllStaleQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the memory &quot;{0}&quot;?.
        /// </summary>
        public static string Msg_Memory_DeleteConfirm {
            get {
                return ResourceManager.GetString("Msg_Memory_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string Msg_Memory_Deleted {
            get {
                return ResourceManager.GetString("Msg_Memory_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete memory: {0}.
        /// </summary>
        public static string Msg_Memory_DeleteFailed {
            get {
                return ResourceManager.GetString("Msg_Memory_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Memory.
        /// </summary>
        public static string Msg_Memory_DeleteTitle {
            get {
                return ResourceManager.GetString("Msg_Memory_DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded.
        /// </summary>
        public static string Msg_Memory_Downloaded {
            get {
                return ResourceManager.GetString("Msg_Memory_Downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download embedding model: {0}.
        /// </summary>
        public static string Msg_Memory_DownloadError {
            get {
                return ResourceManager.GetString("Msg_Memory_DownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The embedding model download did not complete successfully. Please try again..
        /// </summary>
        public static string Msg_Memory_DownloadFailedMessage {
            get {
                return ResourceManager.GetString("Msg_Memory_DownloadFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Failed.
        /// </summary>
        public static string Msg_Memory_DownloadFailedTitle {
            get {
                return ResourceManager.GetString("Msg_Memory_DownloadFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embedding model downloaded and ready to use..
        /// </summary>
        public static string Msg_Memory_EmbeddingModelDownloaded {
            get {
                return ResourceManager.GetString("Msg_Memory_EmbeddingModelDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regenerated embeddings for {0} of {1} memories..
        /// </summary>
        public static string Msg_Memory_EmbeddingsRegenerated {
            get {
                return ResourceManager.GetString("Msg_Memory_EmbeddingsRegenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported.
        /// </summary>
        public static string Msg_Memory_Exported {
            get {
                return ResourceManager.GetString("Msg_Memory_Exported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memories exported to {0}.
        /// </summary>
        public static string Msg_Memory_ExportedTo {
            get {
                return ResourceManager.GetString("Msg_Memory_ExportedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to export memories: {0}.
        /// </summary>
        public static string Msg_Memory_ExportFailed {
            get {
                return ResourceManager.GetString("Msg_Memory_ExportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data you entered is not valid JSON. Please correct it and try again..
        /// </summary>
        public static string Msg_Memory_InvalidJsonMessage {
            get {
                return ResourceManager.GetString("Msg_Memory_InvalidJsonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid JSON.
        /// </summary>
        public static string Msg_Memory_InvalidJsonTitle {
            get {
                return ResourceManager.GetString("Msg_Memory_InvalidJsonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last accessed {0}.
        /// </summary>
        public static string Msg_Memory_LastAccessed {
            get {
                return ResourceManager.GetString("Msg_Memory_LastAccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory &quot;{0}&quot; has been deleted..
        /// </summary>
        public static string Msg_Memory_MemoryDeleted {
            get {
                return ResourceManager.GetString("Msg_Memory_MemoryDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory updated successfully..
        /// </summary>
        public static string Msg_Memory_MemoryUpdated {
            get {
                return ResourceManager.GetString("Msg_Memory_MemoryUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please download the embedding model first before regenerating embeddings..
        /// </summary>
        public static string Msg_Memory_ModelNotAvailableMessage {
            get {
                return ResourceManager.GetString("Msg_Memory_ModelNotAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Not Available.
        /// </summary>
        public static string Msg_Memory_ModelNotAvailableTitle {
            get {
                return ResourceManager.GetString("Msg_Memory_ModelNotAvailableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No memories older than 90 days found..
        /// </summary>
        public static string Msg_Memory_NoStaleMemories {
            get {
                return ResourceManager.GetString("Msg_Memory_NoStaleMemories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will regenerate vector embeddings for all memories. This may take a moment..
        /// </summary>
        public static string Msg_Memory_RegenerateEmbeddingsMessage {
            get {
                return ResourceManager.GetString("Msg_Memory_RegenerateEmbeddingsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regenerate Embeddings.
        /// </summary>
        public static string Msg_Memory_RegenerateEmbeddingsTitle {
            get {
                return ResourceManager.GetString("Msg_Memory_RegenerateEmbeddingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to regenerate embeddings: {0}.
        /// </summary>
        public static string Msg_Memory_RegenerateFailed {
            get {
                return ResourceManager.GetString("Msg_Memory_RegenerateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string Msg_Memory_Saved {
            get {
                return ResourceManager.GetString("Msg_Memory_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save memory: {0}.
        /// </summary>
        public static string Msg_Memory_SaveFailed {
            get {
                return ResourceManager.GetString("Msg_Memory_SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted {0} stale memories..
        /// </summary>
        public static string Msg_Memory_StaleDeleted {
            get {
                return ResourceManager.GetString("Msg_Memory_StaleDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} memories not accessed in over 90 days:.
        /// </summary>
        public static string Msg_Memory_StaleFound {
            get {
                return ResourceManager.GetString("Msg_Memory_StaleFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stale Memories.
        /// </summary>
        public static string Msg_Memory_StaleReviewTitle {
            get {
                return ResourceManager.GetString("Msg_Memory_StaleReviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research was cancelled..
        /// </summary>
        public static string Msg_Research_Cancelled {
            get {
                return ResourceManager.GetString("Msg_Research_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied.
        /// </summary>
        public static string Msg_Research_Copied {
            get {
                return ResourceManager.GetString("Msg_Research_Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported.
        /// </summary>
        public static string Msg_Research_Exported {
            get {
                return ResourceManager.GetString("Msg_Research_Exported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research failed: {0}.
        /// </summary>
        public static string Msg_Research_Failed {
            get {
                return ResourceManager.GetString("Msg_Research_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full research exported to clipboard..
        /// </summary>
        public static string Msg_Research_FullResearchExported {
            get {
                return ResourceManager.GetString("Msg_Research_FullResearchExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No AI provider configured for Research mode. Please add one in Settings..
        /// </summary>
        public static string Msg_Research_NoProviderConfigured {
            get {
                return ResourceManager.GetString("Msg_Research_NoProviderConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research result copied to clipboard..
        /// </summary>
        public static string Msg_Research_ResultCopied {
            get {
                return ResourceManager.GetString("Msg_Research_ResultCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete a provider that is assigned to a mode. Please reassign first..
        /// </summary>
        public static string Msg_Settings_CannotDeleteAssignedProvider {
            get {
                return ResourceManager.GetString("Msg_Settings_CannotDeleteAssignedProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built-in templates cannot be deleted..
        /// </summary>
        public static string Msg_Settings_CannotDeleteBuiltInTemplate {
            get {
                return ResourceManager.GetString("Msg_Settings_CannotDeleteBuiltInTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete the default template. Please set another template as default first..
        /// </summary>
        public static string Msg_Settings_CannotDeleteDefaultTemplate {
            get {
                return ResourceManager.GetString("Msg_Settings_CannotDeleteDefaultTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflict.
        /// </summary>
        public static string Msg_Settings_Conflict {
            get {
                return ResourceManager.GetString("Msg_Settings_Conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed: {0}.
        /// </summary>
        public static string Msg_Settings_ConnectionFailed {
            get {
                return ResourceManager.GetString("Msg_Settings_ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection successful! Provider supports tool calling and streaming..
        /// </summary>
        public static string Msg_Settings_ConnectionSuccess {
            get {
                return ResourceManager.GetString("Msg_Settings_ConnectionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected, but streaming is not supported. Responses will load all at once..
        /// </summary>
        public static string Msg_Settings_ConnectionSuccessNoStreaming {
            get {
                return ResourceManager.GetString("Msg_Settings_ConnectionSuccessNoStreaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected, but tool calling is not supported. Memory and reminders will not be available in Assistant mode..
        /// </summary>
        public static string Msg_Settings_ConnectionSuccessNoTools {
            get {
                return ResourceManager.GetString("Msg_Settings_ConnectionSuccessNoTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected, but neither tool calling nor streaming is supported..
        /// </summary>
        public static string Msg_Settings_ConnectionSuccessNoToolsNoStreaming {
            get {
                return ResourceManager.GetString("Msg_Settings_ConnectionSuccessNoToolsNoStreaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a custom template. The prompt is generated dynamically based on the template&apos;s configured fields..
        /// </summary>
        public static string Msg_Settings_CustomTemplatePromptInfo {
            get {
                return ResourceManager.GetString("Msg_Settings_CustomTemplatePromptInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This hotkey is already assigned to {0} mode..
        /// </summary>
        public static string Msg_Settings_HotkeyAlreadyAssigned {
            get {
                return ResourceManager.GetString("Msg_Settings_HotkeyAlreadyAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not set.
        /// </summary>
        public static string Msg_Settings_HotkeyNotSet {
            get {
                return ResourceManager.GetString("Msg_Settings_HotkeyNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model download was cancelled..
        /// </summary>
        public static string Msg_Settings_ModelDownloadCancelled {
            get {
                return ResourceManager.GetString("Msg_Settings_ModelDownloadCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whisper model downloaded successfully..
        /// </summary>
        public static string Msg_Settings_ModelDownloadCompleted {
            get {
                return ResourceManager.GetString("Msg_Settings_ModelDownloadCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model download failed: {0}.
        /// </summary>
        public static string Msg_Settings_ModelDownloadFailed {
            get {
                return ResourceManager.GetString("Msg_Settings_ModelDownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now using {0} voice..
        /// </summary>
        public static string Msg_Settings_NowUsingVoice {
            get {
                return ResourceManager.GetString("Msg_Settings_NowUsingVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template added successfully..
        /// </summary>
        public static string Msg_Settings_TemplateAdded {
            get {
                return ResourceManager.GetString("Msg_Settings_TemplateAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template deleted successfully..
        /// </summary>
        public static string Msg_Settings_TemplateDeleted {
            get {
                return ResourceManager.GetString("Msg_Settings_TemplateDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template updated successfully..
        /// </summary>
        public static string Msg_Settings_TemplateUpdated {
            get {
                return ResourceManager.GetString("Msg_Settings_TemplateUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice Changed.
        /// </summary>
        public static string Msg_Settings_VoiceChanged {
            get {
                return ResourceManager.GetString("Msg_Settings_VoiceChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice {0} downloaded successfully..
        /// </summary>
        public static string Msg_Settings_VoiceDownloaded {
            get {
                return ResourceManager.GetString("Msg_Settings_VoiceDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice download failed: {0}.
        /// </summary>
        public static string Msg_Settings_VoiceDownloadFailed {
            get {
                return ResourceManager.GetString("Msg_Settings_VoiceDownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set voice: {0}.
        /// </summary>
        public static string Msg_Settings_VoiceSetFailed {
            get {
                return ResourceManager.GetString("Msg_Settings_VoiceSetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Msg_Success {
            get {
                return ResourceManager.GetString("Msg_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added.
        /// </summary>
        public static string Msg_Todo_Added {
            get {
                return ResourceManager.GetString("Msg_Todo_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add todo: {0}.
        /// </summary>
        public static string Msg_Todo_AddFailed {
            get {
                return ResourceManager.GetString("Msg_Todo_AddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to complete todo: {0}.
        /// </summary>
        public static string Msg_Todo_CompleteFailed {
            get {
                return ResourceManager.GetString("Msg_Todo_CompleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete &quot;{0}&quot;?.
        /// </summary>
        public static string Msg_Todo_DeleteConfirm {
            get {
                return ResourceManager.GetString("Msg_Todo_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string Msg_Todo_Deleted {
            get {
                return ResourceManager.GetString("Msg_Todo_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete todo: {0}.
        /// </summary>
        public static string Msg_Todo_DeleteFailed {
            get {
                return ResourceManager.GetString("Msg_Todo_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Todo.
        /// </summary>
        public static string Msg_Todo_DeleteTitle {
            get {
                return ResourceManager.GetString("Msg_Todo_DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} completed.
        /// </summary>
        public static string Msg_Todo_ProgressText {
            get {
                return ResourceManager.GetString("Msg_Todo_ProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todo &quot;{0}&quot; added..
        /// </summary>
        public static string Msg_Todo_TodoAdded {
            get {
                return ResourceManager.GetString("Msg_Todo_TodoAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todo &quot;{0}&quot; deleted..
        /// </summary>
        public static string Msg_Todo_TodoDeleted {
            get {
                return ResourceManager.GetString("Msg_Todo_TodoDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todo updated successfully..
        /// </summary>
        public static string Msg_Todo_TodoUpdated {
            get {
                return ResourceManager.GetString("Msg_Todo_TodoUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to uncomplete todo: {0}.
        /// </summary>
        public static string Msg_Todo_UncompleteFailed {
            get {
                return ResourceManager.GetString("Msg_Todo_UncompleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        public static string Msg_Todo_Updated {
            get {
                return ResourceManager.GetString("Msg_Todo_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update todo: {0}.
        /// </summary>
        public static string Msg_Todo_UpdateFailed {
            get {
                return ResourceManager.GetString("Msg_Todo_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Msg_Warning {
            get {
                return ResourceManager.GetString("Msg_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss.
        /// </summary>
        public static string Notification_Dismiss {
            get {
                return ResourceManager.GetString("Notification_Dismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder.
        /// </summary>
        public static string Notification_Reminder {
            get {
                return ResourceManager.GetString("Notification_Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder: {0}.
        /// </summary>
        public static string Notification_ReminderInApp {
            get {
                return ResourceManager.GetString("Notification_ReminderInApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snooze.
        /// </summary>
        public static string Notification_Snooze {
            get {
                return ResourceManager.GetString("Notification_Snooze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string Snackbar_Cancelled {
            get {
                return ResourceManager.GetString("Snackbar_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Snackbar_Error {
            get {
                return ResourceManager.GetString("Snackbar_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Snackbar_Success {
            get {
                return ResourceManager.GetString("Snackbar_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Snackbar_Warning {
            get {
                return ResourceManager.GetString("Snackbar_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Assistant.
        /// </summary>
        public static string Tray_CloseAssistant {
            get {
                return ResourceManager.GetString("Tray_CloseAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Optimize.
        /// </summary>
        public static string Tray_CloseOptimize {
            get {
                return ResourceManager.GetString("Tray_CloseOptimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Research.
        /// </summary>
        public static string Tray_CloseResearch {
            get {
                return ResourceManager.GetString("Tray_CloseResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Tray_Exit {
            get {
                return ResourceManager.GetString("Tray_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Assistant.
        /// </summary>
        public static string Tray_OpenAssistant {
            get {
                return ResourceManager.GetString("Tray_OpenAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Optimize.
        /// </summary>
        public static string Tray_OpenOptimize {
            get {
                return ResourceManager.GetString("Tray_OpenOptimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Research.
        /// </summary>
        public static string Tray_OpenResearch {
            get {
                return ResourceManager.GetString("Tray_OpenResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pia - Personal Intelligent Assistant.
        /// </summary>
        public static string Tray_Tooltip {
            get {
                return ResourceManager.GetString("Tray_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pia - Click to open.
        /// </summary>
        public static string Tray_TooltipIdle {
            get {
                return ResourceManager.GetString("Tray_TooltipIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pia - {0} window(s) open.
        /// </summary>
        public static string Tray_TooltipWindowCount {
            get {
                return ResourceManager.GetString("Tray_TooltipWindowCount", resourceCulture);
            }
        }
    }
}
